Description of timeString
Home > mfiles > timeString.m
timeString
PURPOSE
timeString returns the current time and date in a convenient string format.
SYNOPSIS
function s = timeString()
DESCRIPTION
 timeString returns the current time and date in a convenient string format.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
LTUsegmentMap LTUsegmentMap - segment map using a network of linear threshold units.
centerSurround centerSurround - computes center-surround difference maps.
centerSurroundTopDown centerSurroundTopDown - pseudo center-surround for top-down maps.
combineMaps combineMaps - returns the sum of a vector of maps.
computeAllSaliencyMaps computeAllSaliencyMaps - computes the saliency maps for many images.
emptyMap emptyMap - creates an empty map.
estimateShape estimateShape - estimates the shape of the attended proto-object region.
fastSegmentMap fastSegmentMap - segment map around a seedPoint.
gaborFilterMap gaborFilterMap - compute a gabor-filtered version of a map.
initializeImage initializeImage - initializes an image structure.
makeBlueYellowPyramid makeBlueYellowPyramid - creates a blue-yellow opponency pyramid.
makeDyadicPyramid makeDyadicPyramid - creates a dyadic Gaussian pyramid.
makeHuePyramid makeHuePyramid - creates a hue distance pyramid.
makeIntensityPyramid makeIntensityPyramid - creates an intensity pyramid.
makeOrientationPyramid makeOrientationPyramid - creates an orientation pyramid.
makeRedGreenPyramid makeRedGreenPyramid - creates a red-green opponency pyramid
makeSaliencyMap makeSaliencyMap - creates a saliency map for an image.
makeSqrt2Pyramid makeSqrt2Pyramid - creates a sqrt(2) Gaussian pyramid.
SOURCE CODE
% timeString returns the current time and date in a convenient string format.
% This file is part of the SaliencyToolbox - Copyright (C) 2006-2008
% by Dirk B. Walther and the California Institute of Technology.
% See the enclosed LICENSE.TXT document for the license agreement.
% More information about this project is available at:
% http://www.saliencytoolbox.net
function s = timeString()
t = clock;
d = date;
s = sprintf('%02d:%02d:%04.1f on %s',t(4),t(5),t(6),d);