function binaryFileReader(inBinFile)
%     hbfr1 = video.BinaryFileReader(...
%                 'Filename',inBinFile, ...
%                 'VideoFormat','Custom', ...
%                 'BitstreamFormat','Planar', ...
%                 'VideoComponentCount',1, ...
%                 'VideoComponentSizes',[544 720], ...
%                 'SignedData',true, ...
%                 'VideoComponentBits',16);
    hbfr2 = video.BinaryFileReader(...
                'Filename',inBinFile, ...
                'VideoFormat','Custom', ...
                'BitstreamFormat','Planar', ...
                'VideoComponentCount',1, ...
                'VideoComponentSizes',[544 720], ...
                'VideoComponentBits',8);   
            
    hvideo1 = video.VideoPlayer('WindowCaption', 'Original Video');
    hvideo1.WindowPosition(1) = 0;
    hvideo1.WindowPosition(2) = 0;
    hvideo1.WindowPosition([4 3]) = [544 720];
    
    while (~isDone(hbfr2))
        sm2 = step(hbfr2);
        step(hvideo1,sm2);
    end
    
    close(hbfr2);
    close(hvideo1);
end